# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Configure Git
      run: |
        git config --add safe.directory '*'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install vt100logging jinja2 markdown
    - name: Parse libraries
      run: |
        python library-parser/library-parser.py libraries.json
    - name: Generate website
      run: |
        python website-generator/website-generator.py libraries.json build
    - uses: jsmrcaga/action-netlify-deploy@v2.0.0
      with:
        NETLIFY_AUTH_TOKEN: ${{ secrets.MY_NETLIFY_TOKEN_SECRET }}
        NETLIFY_SITE_ID: ${{ secrets.MY_NETLIFY_SITE_ID }}
        NETLIFY_DEPLOY_TO_PROD: true
        install_command: "echo Nothing to install here"
        build_command: "echo Nothing to build here"